FROM dotnet-sdk-debug:8.0 AS dev

WORKDIR /src

COPY . .

EXPOSE 80
EXPOSE 5005     

HEALTHCHECK --interval=10s --timeout=3s --start-period=10s --retries=3 \
  CMD curl --silent --fail http://localhost:80/health || exit 1

ENTRYPOINT ["dotnet", "watch", "--project", "OrderService/OrderService.csproj", "run", "--urls=http://0.0.0.0:80"]
