version: '3.8'
services:

  orderservice:
    container_name: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    volumes:
      - ./OrderService:/src
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ./logs:/app/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      notificationdb:
        condition: service_healthy
    ports:
      - "5000:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    networks:
      - elastic-net

  paymentservice:
    container_name: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    volumes:
      - ./PaymentService:/src
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      rabbitmq:
        condition: service_healthy
      notificationdb:
        condition: service_healthy
    ports:
      - "5001:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    networks:
      - elastic-net
  
  notificationservice:
    container_name: notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "5002:80"
    volumes:
      - ./NotificationService:/src
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      rabbitmq:
        condition: service_healthy
      notificationdb:
        condition: service_healthy
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    networks:
      - elastic-net

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    networks:
      - elastic-net
  
volumes:
  seq-data:
    name: seq-data
    
networks:
  elastic-net:
    name: elastic-net
    driver: bridge
