version: '3.8'

services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - network.host=0.0.0.0  # Adição crítica
  #   ports:
  #     - "9200:9200"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic-net

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.0
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - XPACK_SECURITY_ENABLED=false
  #     - NODE_OPTIONS="--openssl-legacy-provider"
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   networks:
  #     - elastic-net
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # jaeger:
  #   image: jaegertracing/all-in-one:1.56
  #   container_name: jaeger
  #   ports:
  #     - 16686:16686   # UI
  #     - 4317:4317     # gRPC (OTLP)
  #     - 4318:4318     # HTTP (OTLP)
  #   networks:
  #     - elastic-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - elastic-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - elastic-net
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - elastic-net


volumes:
  grafana-storage:
    name: grafana-storage
    driver: local
  es-data:
    name: es-data
    driver: local

        
networks:
  elastic-net:
    external: true
