version: '3.8'
services:
  orderservice:
    container_name: orderservice
    depends_on:
      - orderdb
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    volumes:
      - ./OrderService:/src
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5000:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1

  paymentservice:
    container_name: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    volumes:
      - ./PaymentService:/src
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5001:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1