version: '3.8'

services:
  orderservice:
    container_name: orderservice
    depends_on:
      - orderdb
    build:
      context: ./OrderService
    volumes:
      - ./OrderService:/src
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5000:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1      