global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['orderservice:80']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']


  # - job_name: 'payment-service'
  #   static_configs:
  #     - targets: ['host.docker.internal:5001']

  # - job_name: 'notification-service'
  #   static_configs:
  #     - targets: ['host.docker.internal:5002']

