{
 "title": "Monitoramento Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "description": "Uso de CPU em todas as instâncias",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "description": "Uso de memória em porcentagem",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Status dos Serviços",
   "type": "stat",
   "description": "Status dos serviços monitorados",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Uso de Disco",
   "type": "timeseries",
   "description": "Uso de disco em porcentagem",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance) (node_filesystem_avail_bytes) \r\n  / \r\n  avg by (instance) (node_filesystem_size_bytes) \r\n  * 100\r\n)\r\n"
    }
   ]
  }
 ]
}