FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN apt-get update && apt-get install -y unzip curl \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg \
    && apt-get clean

# Define workdir genérico, cada serviço sobrescreve se quiser
WORKDIR /src
